### PR TITLE
Tiny typo fix in iron-icons.html

### PR DESCRIPTION
**Pull request by jnlopar**

### CODE REVIEW

**Comment by notwaldorf** [comment]
Would you mind squashing your commits, please? :)

**Comment by jnlopar** [comment]
Done (i think!) :)

**Comment by jnlopar** [comment]
actually, no, will update when i have it all rebased properly. :(

**Comment by jnlopar** [comment]
There we go. :)

**Comment by notwaldorf** [comment]
Awesome, thanks for putting up with all the annoying steps! :+1:

**Pull request merged**
